services:
  caddy:
    container_name: caddy
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./frontend/build:/srv
    depends_on:
      - app
    networks:
      default:
        aliases:
          - caddy

  app:
    container_name: app
    build:
      context: .
    expose:
      - "10000"
    networks:
      default:
        aliases:
          - app

  ddns:
    container_name: ddns
    build:
      context: ./ddns
    expose:
      - "12345" # for fun
    depends_on:
      - app
    networks:
      default:
        aliases:
          - ddns
      
